Sub PartsFromBOM()
    Dim oAsmDoc As AssemblyDocument
    Set oAsmDoc = ThisApplication.ActiveDocument
    Dim oBOM As BOM
    Set oBOM = oAsmDoc.ComponentDefinition.BOM
    oBOM.PartsOnlyViewEnabled = True
    Dim oPartsOnlyBOMView As BOMView
    Set oPartsOnlyBOMView = oBOM.BOMViews.Item("Parts Only")
    Dim i As Long
    For i = 1 To oPartsOnlyBOMView.BOMRows.Count
        Dim oRow As BOMRow
        Set oRow = oPartsOnlyBOMView.BOMRows.Item(i)
        Dim oCompDef As ComponentDefinition
        Set oCompDef = oRow.ComponentDefinitions.Item(1)
        If TypeName(oCompDef) = "SheetMetalComponentDefinition" Then
            Dim oCompDeff As SheetMetalComponentDefinition
            Set oCompDeff = oCompDef
            Dim oFlatPtn As FlatPattern
            Set oFlatPtn = oCompDeff.FlatPattern
            If Not (oFlatPtn.MassProperties.Area = Null) Then
                oCompDeff.Unfold
            Else
            End If
            MsgBox "Area" & oFlatPtn.MassProperties.Area
        Else
            MsgBox "Not Shit"
        End If
    Next
End Sub
